#!/bin/sh

CONFIG_DIR="${1:-/etc/kubevirt}"
MANIFEST_URL="https://github.com/kubevirt/kubevirt/releases/download"

echo "Downloading release templates from kubevirt/kubevirt"

if [ -z "${versions}" ]; then
   versions=$(git ls-remote --tags https://github.com/kubevirt/kubevirt |  sed 's/.*refs\/tags\///g' | grep -v '\^{}')
fi

for version in ${versions}; do
    echo "Downloading template for ${version}"

    if [ ! -d "${version}" ]; then
    	mkdir "${CONFIG_DIR}/${version}"
    fi

    curl -Lf "${MANIFEST_URL}/${version}/kubevirt.yaml" -o "${CONFIG_DIR}/${version}/kubevirt.yaml"

    echo "Download for ${version} complete"
done
